In [79]:
import pandas as pd
import numpy

In [80]:
df=pd.read_excel('E:/다운로드/cluster.xlsx')

C:\Users\sungyu choi\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:308: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [81]:
df

    Customer_Last_Name  Offer #
0                Smith        2
1                Smith       24
2              Johnson       17
3              Johnson       24
4              Johnson       26
..                 ...      ...
319             Fisher       11
320             Fisher       22
321             Fisher       28
322             Fisher       30
323             Fisher       31

[324 rows x 2 columns]

In [82]:
pt=df.pivot_table(index = ['Offer #'], columns = ['Customer_Last_Name'], aggfunc=len, fill_value=0)
pt

Customer_Last_Name,Adams,Allen,Anderson,Bailey,Baker,Barnes,Bell,Bennett,Brooks,Brown,...,Turner,Walker,Ward,Watson,White,Williams,Wilson,Wood,Wright,Young
Offer #,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,1,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,1
7,0,0,0,1,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
8,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,1,0,0,0
9,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
19,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1,0,0,0,0,0,0,1,0,1,...,0,1,0,1,0,0,0,0,0,0
30,1,0,0,1,0,0,0,0,0,1,...,0,0,0,0,1,0,1,0,0,0
31,0,0,0,0,1,1,0,0,0,0,...,1,0,0,0,0,1,0,1,0,1
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [83]:
pt_T=pt.T

In [84]:
pt_T

Offer #,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,32
Customer_Last_Name,,,,,,,,,,,,,,,,,,,,,
Adams,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
Allen,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
Anderson,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
Bailey,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Baker,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Williams,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Wilson,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
Wood,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
Wright,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Young,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1

In [85]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [86]:
from sklearn.metrics import silhouette_score

In [87]:
kmeans=KMeans(n_clusters=4).fit(pt_T)
label=kmeans.labels_
sil_coeff=silhouette_score(pt_T , label , metric='euclidean')

In [88]:
sil_coeff

0.12225405622700572

In [89]:
kmeans=KMeans(n_clusters=4, max_iter=1000).fit(pt_T)
pt_T['clusters']=kmeans.labels_

In [90]:
pt_T

Offer #,1,2,3,4,5,6,7,8,9,10,...,24,25,26,27,28,29,30,31,32,clusters
Customer_Last_Name,,,,,,,,,,,,,,,,,,,,,
Adams,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
Allen,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
Anderson,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,3
Bailey,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Baker,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Williams,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
Wilson,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
Wood,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,2
Wright,0,0,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
Young,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1

In [91]:
sil={}
for i in range(3,6):
    kmeans=KMeans(n_clusters=i).fit(pt_T)
    label=kmeans.labels_
    sil_coeff=silhouette_score(pt_T,label,metric='euclidean')
    sil[i]=sil_coeff

In [92]:
sil

{3: 0.20563775253895827, 4: 0.2180941090403112, 5: 0.20407584041018378}

In [93]:
wine_df=pd.read_excel('E:/다운로드/cluster.xlsx', sheet_name='OfferInformation')

C:\Users\sungyu choi\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:308: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [94]:
wine_df

,Offer,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak
0,1,January,Malbec,72,56,France,False
1,2,January,Pinot Noir,72,17,France,False
2,3,February,Espumante,144,32,Oregon,True
3,4,February,Champagne,72,48,France,True
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True
5,6,March,Prosecco,144,86,Chile,False
6,7,March,Prosecco,6,40,Australia,True
7,8,March,Espumante,6,45,South Africa,False
8,9,April,Chardonnay,144,57,Chile,False
9,10,April,Prosecco,72,52,California,False
10,11,May,Champagne,72,85,France,False
11,12,May,Prosecco,72,83,Australia,False
12,13,May,Merlot,6,43,Chile,False
13,14,June,Merlot,72,64,Chile,False
14,15,June,Cabernet Sauvignon,144,19,Italy,False
15,16,June,Merlot,72,88,California,False
16,17,July,Pinot Noir,12,47,Germany,False
17,18,July,Espumante,6,50,Oregon,False
18,19,July,Champagne,12,66,Germany,False
19,20,August,Cabernet Sauvignon,72,82,Italy,False
20,21,August,Champagne,12,50,California,False
21,22,August,Champagne,72,63,France,False
22,23,September,Chardonnay,144,39,South Africa,False
23,24,September,Pinot Noir,6,34,Italy,False
24,25,October,Cabernet Sauvignon,72,59,Oregon,True
25,26,October,Pinot Noir,144,83,Australia,False
26,27,October,Champagne,72,88,New Zealand,False
27,28,November,Cabernet Sauvignon,12,56,France,True
28,29,November,Pinot Grigio,6,87,France,False
29,30,December,Malbec,6,54,France,False
30,31,December,Champagne,72,89,France,False
31,32,December,Cabernet Sauvignon,72,45,Germany,True

In [95]:
wine_df['clus_0']=pt_T[pt_T.clusters==0].sum(axis=0)[:-1]
wine_df['clus_1']=pt_T[pt_T.clusters==1].sum(axis=0)[:-1]
wine_df['clus_2']=pt_T[pt_T.clusters==2].sum(axis=0)[:-1]
wine_df['clus_3']=pt_T[pt_T.clusters==3].sum(axis=0)[:-1]

In [96]:
wine_df #NaN값이 나오는 것은 해결하지 못했다.

,Offer,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,clus_0,clus_1,clus_2,clus_3
0,1,January,Malbec,72,56,France,False,NaN,NaN,NaN,NaN
1,2,January,Pinot Noir,72,17,France,False,0.0,0.0,10.0,0.0
2,3,February,Espumante,144,32,Oregon,True,0.0,0.0,5.0,5.0
3,4,February,Champagne,72,48,France,True,0.0,6.0,0.0,0.0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,0.0,8.0,4.0,0.0
5,6,March,Prosecco,144,86,Chile,False,0.0,2.0,2.0,0.0
6,7,March,Prosecco,6,40,Australia,True,0.0,11.0,1.0,0.0
7,8,March,Espumante,6,45,South Africa,False,12.0,7.0,0.0,0.0
8,9,April,Chardonnay,144,57,Chile,False,11.0,9.0,0.0,0.0
9,10,April,Prosecco,72,52,California,False,1.0,6.0,3.0,0.0
10,11,May,Champagne,72,85,France,False,0.0,5.0,2.0,0.0
11,12,May,Prosecco,72,83,Australia,False,1.0,7.0,5.0,0.0
12,13,May,Merlot,6,43,Chile,False,0.0,4.0,0.0,1.0
13,14,June,Merlot,72,64,Chile,False,6.0,0.0,0.0,0.0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,0.0,5.0,4.0,0.0
15,16,June,Merlot,72,88,California,False,0.0,4.0,2.0,0.0
16,17,July,Pinot Noir,12,47,Germany,False,1.0,3.0,0.0,1.0
17,18,July,Espumante,6,50,Oregon,False,0.0,0.0,0.0,7.0
18,19,July,Champagne,12,66,Germany,False,11.0,3.0,0.0,0.0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,0.0,5.0,0.0,0.0
20,21,August,Champagne,12,50,California,False,0.0,4.0,2.0,0.0
21,22,August,Champagne,72,63,France,False,0.0,4.0,0.0,0.0
22,23,September,Chardonnay,144,39,South Africa,False,0.0,15.0,6.0,0.0
23,24,September,Pinot Noir,6,34,Italy,False,0.0,3.0,2.0,0.0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,0.0,0.0,0.0,12.0
25,26,October,Pinot Noir,144,83,Australia,False,1.0,4.0,1.0,0.0
26,27,October,Champagne,72,88,New Zealand,False,0.0,0.0,4.0,11.0
27,28,November,Cabernet Sauvignon,12,56,France,True,0.0,8.0,1.0,0.0
28,29,November,Pinot Grigio,6,87,France,False,1.0,2.0,3.0,0.0
29,30,December,Malbec,6,54,France,False,16.0,1.0,0.0,0.0
30,31,December,Champagne,72,89,France,False,18.0,1.0,3.0,0.0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,0.0,14.0,3.0,0.0

In [97]:
wine_df.sort_values('clus_0',ascending=False)

,Offer,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,clus_0,clus_1,clus_2,clus_3
30,31,December,Champagne,72,89,France,False,18.0,1.0,3.0,0.0
29,30,December,Malbec,6,54,France,False,16.0,1.0,0.0,0.0
7,8,March,Espumante,6,45,South Africa,False,12.0,7.0,0.0,0.0
18,19,July,Champagne,12,66,Germany,False,11.0,3.0,0.0,0.0
8,9,April,Chardonnay,144,57,Chile,False,11.0,9.0,0.0,0.0
13,14,June,Merlot,72,64,Chile,False,6.0,0.0,0.0,0.0
11,12,May,Prosecco,72,83,Australia,False,1.0,7.0,5.0,0.0
25,26,October,Pinot Noir,144,83,Australia,False,1.0,4.0,1.0,0.0
16,17,July,Pinot Noir,12,47,Germany,False,1.0,3.0,0.0,1.0
9,10,April,Prosecco,72,52,California,False,1.0,6.0,3.0,0.0
28,29,November,Pinot Grigio,6,87,France,False,1.0,2.0,3.0,0.0
20,21,August,Champagne,12,50,California,False,0.0,4.0,2.0,0.0
27,28,November,Cabernet Sauvignon,12,56,France,True,0.0,8.0,1.0,0.0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,0.0,0.0,0.0,12.0
23,24,September,Pinot Noir,6,34,Italy,False,0.0,3.0,2.0,0.0
22,23,September,Chardonnay,144,39,South Africa,False,0.0,15.0,6.0,0.0
21,22,August,Champagne,72,63,France,False,0.0,4.0,0.0,0.0
26,27,October,Champagne,72,88,New Zealand,False,0.0,0.0,4.0,11.0
1,2,January,Pinot Noir,72,17,France,False,0.0,0.0,10.0,0.0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,0.0,5.0,0.0,0.0
17,18,July,Espumante,6,50,Oregon,False,0.0,0.0,0.0,7.0
2,3,February,Espumante,144,32,Oregon,True,0.0,0.0,5.0,5.0
15,16,June,Merlot,72,88,California,False,0.0,4.0,2.0,0.0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,0.0,5.0,4.0,0.0
12,13,May,Merlot,6,43,Chile,False,0.0,4.0,0.0,1.0
10,11,May,Champagne,72,85,France,False,0.0,5.0,2.0,0.0
6,7,March,Prosecco,6,40,Australia,True,0.0,11.0,1.0,0.0
5,6,March,Prosecco,144,86,Chile,False,0.0,2.0,2.0,0.0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,0.0,8.0,4.0,0.0
3,4,February,Champagne,72,48,France,True,0.0,6.0,0.0,0.0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,0.0,14.0,3.0,0.0
0,1,January,Malbec,72,56,France,False,NaN,NaN,NaN,NaN

In [98]:
wine_df.sort_values('clus_1',ascending=False)

,Offer,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,clus_0,clus_1,clus_2,clus_3
22,23,September,Chardonnay,144,39,South Africa,False,0.0,15.0,6.0,0.0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,0.0,14.0,3.0,0.0
6,7,March,Prosecco,6,40,Australia,True,0.0,11.0,1.0,0.0
8,9,April,Chardonnay,144,57,Chile,False,11.0,9.0,0.0,0.0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,0.0,8.0,4.0,0.0
27,28,November,Cabernet Sauvignon,12,56,France,True,0.0,8.0,1.0,0.0
7,8,March,Espumante,6,45,South Africa,False,12.0,7.0,0.0,0.0
11,12,May,Prosecco,72,83,Australia,False,1.0,7.0,5.0,0.0
3,4,February,Champagne,72,48,France,True,0.0,6.0,0.0,0.0
9,10,April,Prosecco,72,52,California,False,1.0,6.0,3.0,0.0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,0.0,5.0,4.0,0.0
10,11,May,Champagne,72,85,France,False,0.0,5.0,2.0,0.0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,0.0,5.0,0.0,0.0
25,26,October,Pinot Noir,144,83,Australia,False,1.0,4.0,1.0,0.0
12,13,May,Merlot,6,43,Chile,False,0.0,4.0,0.0,1.0
15,16,June,Merlot,72,88,California,False,0.0,4.0,2.0,0.0
20,21,August,Champagne,12,50,California,False,0.0,4.0,2.0,0.0
21,22,August,Champagne,72,63,France,False,0.0,4.0,0.0,0.0
23,24,September,Pinot Noir,6,34,Italy,False,0.0,3.0,2.0,0.0
16,17,July,Pinot Noir,12,47,Germany,False,1.0,3.0,0.0,1.0
18,19,July,Champagne,12,66,Germany,False,11.0,3.0,0.0,0.0
5,6,March,Prosecco,144,86,Chile,False,0.0,2.0,2.0,0.0
28,29,November,Pinot Grigio,6,87,France,False,1.0,2.0,3.0,0.0
29,30,December,Malbec,6,54,France,False,16.0,1.0,0.0,0.0
30,31,December,Champagne,72,89,France,False,18.0,1.0,3.0,0.0
17,18,July,Espumante,6,50,Oregon,False,0.0,0.0,0.0,7.0
2,3,February,Espumante,144,32,Oregon,True,0.0,0.0,5.0,5.0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,0.0,0.0,0.0,12.0
13,14,June,Merlot,72,64,Chile,False,6.0,0.0,0.0,0.0
26,27,October,Champagne,72,88,New Zealand,False,0.0,0.0,4.0,11.0
1,2,January,Pinot Noir,72,17,France,False,0.0,0.0,10.0,0.0
0,1,January,Malbec,72,56,France,False,NaN,NaN,NaN,NaN

In [99]:
wine_df.sort_values('clus_2',ascending=False)

,Offer,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,clus_0,clus_1,clus_2,clus_3
1,2,January,Pinot Noir,72,17,France,False,0.0,0.0,10.0,0.0
22,23,September,Chardonnay,144,39,South Africa,False,0.0,15.0,6.0,0.0
11,12,May,Prosecco,72,83,Australia,False,1.0,7.0,5.0,0.0
2,3,February,Espumante,144,32,Oregon,True,0.0,0.0,5.0,5.0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,0.0,8.0,4.0,0.0
26,27,October,Champagne,72,88,New Zealand,False,0.0,0.0,4.0,11.0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,0.0,5.0,4.0,0.0
30,31,December,Champagne,72,89,France,False,18.0,1.0,3.0,0.0
28,29,November,Pinot Grigio,6,87,France,False,1.0,2.0,3.0,0.0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,0.0,14.0,3.0,0.0
9,10,April,Prosecco,72,52,California,False,1.0,6.0,3.0,0.0
10,11,May,Champagne,72,85,France,False,0.0,5.0,2.0,0.0
23,24,September,Pinot Noir,6,34,Italy,False,0.0,3.0,2.0,0.0
15,16,June,Merlot,72,88,California,False,0.0,4.0,2.0,0.0
5,6,March,Prosecco,144,86,Chile,False,0.0,2.0,2.0,0.0
20,21,August,Champagne,12,50,California,False,0.0,4.0,2.0,0.0
27,28,November,Cabernet Sauvignon,12,56,France,True,0.0,8.0,1.0,0.0
6,7,March,Prosecco,6,40,Australia,True,0.0,11.0,1.0,0.0
25,26,October,Pinot Noir,144,83,Australia,False,1.0,4.0,1.0,0.0
3,4,February,Champagne,72,48,France,True,0.0,6.0,0.0,0.0
29,30,December,Malbec,6,54,France,False,16.0,1.0,0.0,0.0
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,0.0,0.0,0.0,12.0
21,22,August,Champagne,72,63,France,False,0.0,4.0,0.0,0.0
7,8,March,Espumante,6,45,South Africa,False,12.0,7.0,0.0,0.0
12,13,May,Merlot,6,43,Chile,False,0.0,4.0,0.0,1.0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,0.0,5.0,0.0,0.0
18,19,July,Champagne,12,66,Germany,False,11.0,3.0,0.0,0.0
17,18,July,Espumante,6,50,Oregon,False,0.0,0.0,0.0,7.0
8,9,April,Chardonnay,144,57,Chile,False,11.0,9.0,0.0,0.0
13,14,June,Merlot,72,64,Chile,False,6.0,0.0,0.0,0.0
16,17,July,Pinot Noir,12,47,Germany,False,1.0,3.0,0.0,1.0
0,1,January,Malbec,72,56,France,False,NaN,NaN,NaN,NaN

In [100]:
wine_df.sort_values('clus_3',ascending=False)

,Offer,Campaign,Varietal,Minimum Qty (kg),Discount (%),Origin,Past Peak,clus_0,clus_1,clus_2,clus_3
24,25,October,Cabernet Sauvignon,72,59,Oregon,True,0.0,0.0,0.0,12.0
26,27,October,Champagne,72,88,New Zealand,False,0.0,0.0,4.0,11.0
17,18,July,Espumante,6,50,Oregon,False,0.0,0.0,0.0,7.0
2,3,February,Espumante,144,32,Oregon,True,0.0,0.0,5.0,5.0
12,13,May,Merlot,6,43,Chile,False,0.0,4.0,0.0,1.0
16,17,July,Pinot Noir,12,47,Germany,False,1.0,3.0,0.0,1.0
29,30,December,Malbec,6,54,France,False,16.0,1.0,0.0,0.0
28,29,November,Pinot Grigio,6,87,France,False,1.0,2.0,3.0,0.0
27,28,November,Cabernet Sauvignon,12,56,France,True,0.0,8.0,1.0,0.0
30,31,December,Champagne,72,89,France,False,18.0,1.0,3.0,0.0
25,26,October,Pinot Noir,144,83,Australia,False,1.0,4.0,1.0,0.0
18,19,July,Champagne,12,66,Germany,False,11.0,3.0,0.0,0.0
23,24,September,Pinot Noir,6,34,Italy,False,0.0,3.0,2.0,0.0
22,23,September,Chardonnay,144,39,South Africa,False,0.0,15.0,6.0,0.0
21,22,August,Champagne,72,63,France,False,0.0,4.0,0.0,0.0
20,21,August,Champagne,12,50,California,False,0.0,4.0,2.0,0.0
19,20,August,Cabernet Sauvignon,72,82,Italy,False,0.0,5.0,0.0,0.0
1,2,January,Pinot Noir,72,17,France,False,0.0,0.0,10.0,0.0
15,16,June,Merlot,72,88,California,False,0.0,4.0,2.0,0.0
14,15,June,Cabernet Sauvignon,144,19,Italy,False,0.0,5.0,4.0,0.0
13,14,June,Merlot,72,64,Chile,False,6.0,0.0,0.0,0.0
11,12,May,Prosecco,72,83,Australia,False,1.0,7.0,5.0,0.0
10,11,May,Champagne,72,85,France,False,0.0,5.0,2.0,0.0
9,10,April,Prosecco,72,52,California,False,1.0,6.0,3.0,0.0
8,9,April,Chardonnay,144,57,Chile,False,11.0,9.0,0.0,0.0
7,8,March,Espumante,6,45,South Africa,False,12.0,7.0,0.0,0.0
6,7,March,Prosecco,6,40,Australia,True,0.0,11.0,1.0,0.0
5,6,March,Prosecco,144,86,Chile,False,0.0,2.0,2.0,0.0
4,5,February,Cabernet Sauvignon,144,44,New Zealand,True,0.0,8.0,4.0,0.0
3,4,February,Champagne,72,48,France,True,0.0,6.0,0.0,0.0
31,32,December,Cabernet Sauvignon,72,45,Germany,True,0.0,14.0,3.0,0.0
0,1,January,Malbec,72,56,France,False,NaN,NaN,NaN,NaN